#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Pointer-PP
version:      1.00
version_from: PP.pm
installdirs:  site
requires:
    B:                             1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
